NewsPaper3/NewsPaper3/urls.py
from django.contrib import admin
from django.urls import path, include
from news3.views import upgrade_me

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('news3.urls')),
    path('sign/', include('allauth.urls')),
    path('sign/upgrade/', upgrade_me, name='upgrade')

]


NewsPaper3/news3/urls.py
from django.urls import path
from .views import IndexView

from .views import NewsList, Search, NewsDetailView, NewsCreateView, NewsUpdateView, NewsDeleteView, CategoryView, \
    CatsView, SubscribeToCategory, UnSubscribeToCategory  # импортируем наше представление

urlpatterns = [

    path('', IndexView.as_view()),
    path('news/', NewsList.as_view()),
    path('news/search/', Search.as_view()),
    path('<int:pk>/', NewsDetailView.as_view(), name='news_detail'),  # Ссылка на детали товара
    path('create/', NewsCreateView.as_view(), name='news_create'),
    path('update/<int:pk>', NewsUpdateView.as_view(), name='news_update'),
    path('delete/<int:pk>', NewsDeleteView.as_view(), name='news_delete'),
    path('news/category/', CategoryView.as_view(), name='category'),
    path('news/category/<int:pk>', CatsView.as_view(), name='cats'),
    path('news/category/<int:pk>/subscribe/', SubscribeToCategory.as_view(), name='subscribe'),
    path('news/category/<int:pk>/unsubscribe/', UnSubscribeToCategory.as_view(), name='unsubscribe'),
]

NewsPaper3/news3/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.cache import cache

class News(models.Model):
    date = models.DateField(auto_now_add=True)
    header = models.CharField(max_length=50, unique=True)
    description = models.TextField(unique=True)
    email = models.EmailField()
    cat = models.ManyToManyField('Category')

    @property
    def on_stock(self):
        return self.quantity > 0

    def __str__(self):
        return f'{self.date} {self.header} {self.description[:20]} {self.email} {self.cat}'

    def get_absolute_url(self):
        return f'/news/{self.id}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs) # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'news-{self.pk}') # затем удаляем его из кэша, чтобы сбросить его


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)  # названия категорий тоже не должны повторяться
    user = models.ManyToManyField(User, 'UsersSubscribed')

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return f'/news/category/{self.id}'


class UsersSubscribed(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user} is subscribed to category {self.category}'


NewsPaper3/templates/base.html
<html>
    <head>
        <title>{% block head_title %}{% endblock head_title %}</title>
    </head>
    <body>
        {% block body %}
        {% block content %}
        {% endblock content %}
        {% endblock body %}
        {% block extra_body %}
        {% endblock extra_body %}
    </body>
</html>

NewsPaper3/templates/category.html
{% include 'flatpages/default.html' %}

{% block content %}
<h2> Категории новостей </h2>

{% for c in category %}
<li><a href={{ c.get_absolute_url }}>{{ c.name }}</a></li>
{% endfor %}
{% endblock %}

NewsPaper3/templates/cats.html


{% block content %}

{% include 'news_detail.html' %}
    <button> <a href="{% url 'subscribe' category.id  %}"> Подписаться на категорию {{ category.name }} </a> </button>

    <button> <a href="{% url 'unsubscribe' category.id  %}"> Отписаться от категории {{ category.name }} </a> </button>


<ul>
  {% for news in category.news_set.all %}
    <li>{{ news.header }}</li>
  {% empty %}
    <li>В этой категории нет новостей</li>
  {% endfor %}

    {% endblock content %}

NewsPaper3/templates/login.html
{% extends "main.html" %}
{% block content %}
<h2> Войти в систему </h2>
<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>

    <input type="submit" value="Войти">
</form>
<button><a href="/accounts/signup"> Регистрация </a></button>
{% endblock %}

NewsPaper3/templates/logout.html
{% extends "main.html" %}


{% block content %}
<h2> Вы вышли из системы </h2>
{% endblock %}

NewsPaper3/templates/mail_to_subscribers.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ header }}</title>
</head>
<body>
    <h2>{{ hello_text }}</h2>
    <p>{{ description|truncatechars:50 }}</p>
</body>
</html>

NewsPaper3/templates/news.html
{% extends 'flatpages/default.html' %}
{% load cache %}
{% cache 60 news.html %}

{% block title %} AllNEWS {% endblock title %}


{% block content %}
<a href="{% url 'news_create' %}">Добавить новую новость</a> <br>

<form method="POST">
    {% csrf_token %}
    {{ form }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    <input type="submit" value="Отправить">
</form>

    <table>
        <thead>
            <th>
                Заголовок
            </th>
            <th>
                Дата
            </th>
            <th>
                Краткое содержание
            </th>
        </thead>
        {% for news in filter.qs %}
         <tr>
             <td>
                 <a href="{% url 'news_detail' news.id %}">{{ news.header|title }}</a> <!-- При нажатии на имя товара в таблице нас теперь будет перекидывать на страницу с информацией о товаре -->
                 <a href="{% url 'news_update' news.id %}"><u>Редактировать</u></a>
                 <a href="{% url 'news_delete' news.id %}"><u> Удалить </u></a>

             </td>

             <td>
                {{ news.date }}
             </td>
             <td>
                {{ news.header|title }}
             </td>
             <td>
                {{ news.description }}
             </td>
             <td>
                {{ news.category }}
             </td>
         </tr>
        {% endfor %}
    </table>

        {% if page_obj.has_previous %}
        <a href="?page=1">First</a>
        <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}


    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>>></a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}



{% endblock content %}
{% endcache %}

NewsPaper3/templates/news_create.html
{% extends 'flatpages/default.html' %}

{% block title %} News list {% endblock title %}

{% block content %}
<h3>Инфо о новости</h3>
<form method="POST">
    {% csrf_token %}
    {{ form }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    <input type="submit" value="Добавить новость">
</form>
{% endblock content %}

NewsPaper3/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block title %} DELETE NEWS {% endblock title %}


{% block content %}
    <table>
        <thead>
            <th>
                Дата
            </th>
            <th>
                Заголовок
            </th>
            <th>
                Краткое содержание
            </th>
      </thead>
        <tr>
             <td>
                {{ news.date }}
            </td>
            <td>
                {{ news.header }}
            </td>
            <td>
                {{ news.description }}
            </td>
        </tr>
    </table>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="подтвердить"></form>

{% endblock content %}

NewsPaper3/templates/news_detail.html
{% extends 'flatpages/default.html' %}
{% load cache %}
{% cache 300 news.html %}

{% block title %} DETAIL NEWS {% endblock title %}


{% block content %}
    <table>
        <thead>
            <th>
                Дата
            </th>
            <th>
                Заголовок
            </th>
            <th>
                Краткое содержание
            </th>
      </thead>
        <tr>
             <td>
                {{ news.date }}
            </td>
            <td>
                {{ news.header|title }}
            </td>
            <td>
                {{ news.description }}
            </td>
        </tr>
    </table>

{% endblock content %}
{% endcache %}

NewsPaper3/templates/news_update.html
{% extends 'flatpages/default.html' %}

{% block title %} DETAIL NEWS {% endblock title %}


{% block content %}
    <table>
        <thead>
            <th>
                Дата
            </th>
            <th>
                Заголовок
            </th>
            <th>
                Краткое содержание
            </th>
      </thead>
        <tr>
             <td>
                {{ news.date }}
            </td>
            <td>
                {{ news.header }}
            </td>
            <td>
                {{ news.description }}
            </td>
        </tr>
    </table>

{% endblock content %}

NewsPaper3/templates/signup.html
{% extends "main.html" %}

{% block content %}
<h2> Войти в систему </h2>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Продолжить">
</form>
{% endblock %}

NewsPaper3/templates/unsubscribe.html
{% extends 'flatpages/default.html' %} 
 
{% block title %}
Успешная отписка
{% endblock title %}
 
{% block content %}
    <h1>Поздравляем, {{ user.get_username }}!</h1>
        <h2>Вы успешно отписались от категории {{ unsubscribed.name }}!</h2>
{% endblock content %}

NewsPaper3/templates/weekly_mail.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{header}}</title>
</head>
<body>
<h1>{{hello_text}}</h1>
    {% for post in posts %}
        <p>{{ news.username }} [{{ news.creation_date_time| date:'d-M-Y g:i' }}] <a href="{{site_link}}{% url 'details' news.id %}">{{ news.header }}</a></p>
    {% endfor %}
</body>
</html>